### PR TITLE
Automatic Nightly building

### PR DESCRIPTION
**Pull request by Wolvan**
Followup to #2: Make Travis automatically create Nightly versions of pushed commits
Example: https://wolvan.github.io/LuaExplorer/build/

If nightly building is not desired, this PR can be ignored.
Turning off nightly building afterwards is as easy as changing the value of `GH_CI_BRANCH`

**Steps to do before merging this pull request:**
1. Go to https://github.com/Hikiruka/Yuki-FM/generated_pages/new and create a Github.io page for Yuki-FM (You can simply load the readme for example)
2. Activate the Yuki-FM repository on [travis-ci](https://travis-ci.org/)
3. Set the following settings on https://travis-ci.org/Hikiruka/Yuki-FM/settings (replace with your own values of course):
image
An access token can be created [here](https://github.com/settings/tokens). The access token needs the `repo` scope
image
4. Merge this commit. This should trigger Travis to immediately create the first build page
5. Optional: Check out the gh-pages branch, create a QR Code to the file `https://hikiruka.github.io/Yuki-FM/build/Yuki%20FM.cia`, and check the file into `/build/QRCode.jpg` of the branch `gh-pages`

If there are any questions, I'd be glad to answer them.

### CODE REVIEW

**Comment by Wolvan** [comment]
Seems like you didn't follow the steps before merging, which means the nightly building is not yet working. Need help?

**Comment by Hikiruka** [comment]
yeah, im not on my personal pc atm

**Comment by Wolvan** [comment]
Alright, fair enough.

**Comment by Hikiruka** [comment]
I activated Travis. what next ?

**Comment by Wolvan** [comment]
You are using the wrong branch. `features/travis-nightly` was what I used to finish the PR. You should set the GH_CI_BRANCH to `master`

**Comment by Wolvan** [comment]
Set the proper branch, then click the restart button that https://travis-ci.org/Hikiruka/Yuki-FM/builds/155072376 has

**Pull request merged**
